'use strict';

export const USER_ROLES = [
  "ROLE_USER_CREATE",
  "ROLE_USER_READ",
  "ROLE_USER_UPDATE",
  "ROLE_USER_DELETE",
  "ROLE_USER_LISTALL",
  "ROLE_ITEM_CREATE",
  "ROLE_ITEM_READ",
  "ROLE_ITEM_UPDATE",
  "ROLE_ITEM_DELETE",
  "ROLE_ITEM_LISTALL",
  "ROLE_POST_TABLE_ALL"
];

export  const USER_ASSISTENT_ROLE=[
  "ROLE_USER_CREATE",
  "ROLE_USER_READ",
  "ROLE_USER_UPDATE",
  "ROLE_USER_DELETE",
  "ROLE_ITEM_CREATE",
  "ROLE_ITEM_READ",
  "ROLE_ITEM_UPDATE",
  "ROLE_ITEM_DELETE"
];
